version: "3.9"
services:
  # nextjs:
  #   build: ./app
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./app:/usr/src/app
    # depends_on:
    #   - postgres
  # server:
  #   build: ./server
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
